### ISSUE TITLE
Snowpack >= 2.17.1 support

### ISSUE THREAD

**Issue by FlorianLouvetRN** [babichjacob/svelte-add-postcss#1]
Hi,

Just tried this on a totally new project following the readme:
```
npm init svelte@next
npm install
npx use-preset babichjacob/svelte-add-tailwindcss
```

The result when running `npm run dev`is a blank page with this error written `Error: Failed to load /_app/main/generated/root.js: NOT_FOUND` . (same error on build also)

Thanks for all the work here.
 👍

**Comment by pebezo** [comment]
I get this exact message if during `npm init svelte@next` I pick typescript. If I don't pick TS I don't get an error and can see the `Hellow world!`, but Tailwind classes are not used/rendered (may be a separate issue)

**Comment by cbenz** [comment]
[This discussion](https://github.com/snowpackjs/snowpack/discussions/1729#discussioncomment-204842) is related.
